### ISSUE TITLE
How to achieve sparkline?

### ISSUE THREAD

**Issue by bartclaeys** [seigler/neat-charts#1]
I don't succeed in creating a sparkline with this lib. Is there an easy way to disable grid labels, grid lines, fade and marker circle?

**Comment by seigler** [comment]
Hi @bartclaeys, here is an example of a sparkline, including how to set the options to disable grid labels and other unnecessary elements.
https://github.com/seigler/neat-charts/blob/master/demo.php#L83
I hope this helps.

**Comment by bartclaeys** [comment]
Thanks! The answer was right there under my nose :)
